name: RDP con tmate (SIN Verificación de Clave)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Habilitar RDP y Crear Usuario
        run: |
          $Password = "P@ssw0rdFeloxPC2025!"
          net user Runner $Password /add /y
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389

      - name: Iniciar tmate para dar Acceso SSH
        uses: mxschmitt/action-tmate@v3
        with:
          # --- LA LÍNEA MÁS IMPORTANTE ---
          # Esto desactiva la necesidad de una clave pública SSH.
          # Ahora no te dará "Permission denied".
          limit-access-to-actor: false
