name: RDP con tmate (Acceso Directo)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Habilitar RDP y Crear Usuario
        run: |
          $Password = "P@ssw0rdFeloxPC2025!"
          net user Runner $Password /add /y
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389

      - name: Iniciar tmate para dar Acceso SSH
        # Esta acci贸n simplemente abre la conexi贸n y te da la direcci贸n.
        # Se ha quitado la restricci贸n de clave para que puedas entrar.
        uses: mxschmitt/action-tmate@v3
