name: RDP Directo (Solución Final)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Habilitar RDP y Configurar Firewall
        run: |
          # Habilita el servicio de Escritorio Remoto
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          
          # Abre el puerto 3389 en el Firewall de Windows para permitir la conexión
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389

      - name: Crear Usuario y Contraseña
        run: |
          # Genera una contraseña aleatoria y segura
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 16 | ForEach-Object {[char]$_})
          
          # Crea el usuario y lo añade a los grupos correctos
          net user /add Runner $password
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          
          # Guarda las credenciales para el paso final
          echo "RDP_USER=Runner" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "RDP_PASSWORD=$password" | Out-File -FilePath $env:GITHUB_ENV

      - name: Obtener y Mostrar IP Pública
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Mostrar Credenciales de Conexión
        run: |
          Write-Host "================================================================"
          Write-Host "               CREDENCIALES DE ACCESO RDP"
          Write-Host "================================================================"
          Write-Host ""
          Write-Host "   Dirección IP (PC Name): ${{ steps.ip.outputs.ipv4 }}"
          Write-Host "   Usuario:                ${{ env.RDP_USER }}"
          Write-Host "   Contraseña:             ${{ env.RDP_PASSWORD }}"
          Write-Host ""
          Write-Host "   (La conexión puede tardar 1-2 minutos en estar disponible)"
          Write-Host "================================================================"
          
      - name: Mantener la Conexión Activa
        run: Start-Sleep -Seconds 21300
