name: RDP Directo (Versión Final y Simplificada)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Habilitar RDP y Crear Usuario
        run: |
          # Define una contraseña fija y segura que cumple con los requisitos de longitud y complejidad
          $Password = "P@ssw0rdFeloxPC2025!"
          
          # Crea el usuario y establece la contraseña en un solo comando
          net user Runner $Password /add /y
          
          # Añade el usuario a los grupos necesarios
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          
          # Habilita el servicio de Escritorio Remoto
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          
          # Abre el puerto 3389 en el Firewall de Windows
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
          
          # Guarda la contraseña para el paso final
          echo "RDP_PASSWORD=$Password" | Out-File -FilePath $env:GITHUB_ENV
          echo "RDP_USER=Runner" | Out-File -FilePath $env:GITHUB_ENV

      - name: Obtener y Mostrar IP Pública
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Mostrar Credenciales de Conexión
        run: |
          Write-Host "================================================================"
          Write-Host "               CREDENCIALES DE ACCESO RDP"
          Write-Host "================================================================"
          Write-Host ""
          Write-Host "   Dirección IP (PC Name): ${{ steps.ip.outputs.ipv4 }}"
          Write-Host "   Usuario:                ${{ env.RDP_USER }}"
          Write-Host "   Contraseña:             ${{ env.RDP_PASSWORD }}"
          Write-Host ""
          Write-Host "   (La conexión puede tardar 1-2 minutos en estar disponible)"
          Write-Host "================================================================"
          
      - name: Mantener la Conexión Activa
        run: Start-Sleep -Seconds 21300
