name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389

      - name: Create RDP User with Secure Password
        run: |
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 14 | ForEach-Object {[char]$_})
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Install Tailscale
        run: |
          # Descarga e instala Tailscale
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-full-latest.exe" -OutFile "$env:TEMP\tailscale-latest.exe"
          Start-Process -FilePath "$env:TEMP\tailscale-latest.exe" -ArgumentList "/S" -Wait

      - name: Connect Tailscale
        run: |
          # Define la clave de autenticación
          $authKey = "tskey-auth-kp1EruBawo11CNTRL-AEDVE4Nj2BQQFrNBTyeRBQ6gyHPFLevR"
          
          # Inicia sesión con la clave. Este método es a menudo más robusto.
          & "C:\Program Files\Tailscale\tailscale.exe" login --authkey=$authKey --hostname=gh-runner-${{ github.run_id }}
          
          # Espera a que se establezca la conexión
          Start-Sleep -Seconds 15
          
          # Obtiene la IP
          $tsIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
          if (-not $tsIP) {
              Write-Error "Error: No se pudo obtener la dirección IP de Tailscale después de iniciar sesión."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
      
      - name: Display Connection Details
        run: |
          Write-Host "`n=== RDP ACCESS CREDENTIALS ==="
          Write-Host "Address (PC Name): ${{ env.TAILSCALE_IP }}"
          Write-Host "Username: RDP"
          Write-Host "Password: ${{ env.RDP_PASSWORD }}"
          Write-Host "============================`n"
          
          # Bucle para mantener la máquina activa
          while ($true) {
              $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              Write-Host "[$timestamp] RDP session is active. This job will be terminated automatically after 6 hours."
              Start-Sleep -Seconds 300
          }
