name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360 # Límite de 6 horas

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Habilita el Escritorio Remoto y deshabilita la Autenticación a Nivel de Red
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          
          # Abre el puerto de RDP en el Firewall de Windows
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389

      - name: Create RDP User with Secure Password
        run: |
          # Genera una contraseña aleatoria y segura
          $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 14 | ForEach-Object {[char]$_})
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          # Crea el usuario y lo añade a los grupos necesarios
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          
          # Guarda la contraseña para mostrarla al final
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      # --- CAMBIO REALIZADO AQUÍ ---
      # Se reemplaza la instalación manual por la acción oficial de Tailscale
      - name: Install and Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          # La clave de autenticación está directamente aquí
          authkey: "tskey-auth-kp1EruBawo11CNTRL-AEDVE4Nj2BQQFrNBTyeRBQ6gyHPFLevR"
          # (Opcional) Define un nombre de host único para cada ejecución
          hostname: gh-runner-${{ github.run_id }}

      - name: Display Connection Details
        run: |
          # Obtenemos la IP de Tailscale después de que la acción la haya configurado
          $tsIP = tailscale ip -4
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
          
          Write-Host "`n=== RDP ACCESS CREDENTIALS ==="
          Write-Host "Address (PC Name): $tsIP"
          Write-Host "Username: RDP"
          Write-Host "Password: ${{ env.RDP_PASSWORD }}"
          Write-Host "============================`n"
          
          # Bucle para mantener la máquina activa
          while ($true) {
              $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              Write-Host "[$timestamp] RDP session is active. This job will be terminated automatically after 6 hours."
              Start-Sleep -Seconds 300
          }
