name: RDP con playit.gg (Reclamación Manual - Versión Fija)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Habilitar RDP y Crear Usuario
        run: |
          $Password = "P@ssw0rdFeloxPC2025!"
          net user Runner $Password /add /y
          net localgroup administrators Runner /add
          net localgroup "Remote Desktop Users" Runner /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
          echo "RDP_USER=Runner" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "RDP_PASSWORD=$Password" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Iniciar playit.gg y Obtener Enlace de Reclamación
        run: |
          # --- URL DE DESCARGA ESPECÍFICA Y VERIFICADA (v0.15.26) ---
          # Se usa el enlace directo a la versión 0.15.26 para garantizar la estabilidad.
          Invoke-WebRequest -Uri 'https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe' -OutFile "C:\playit.exe"
          
          # Inicia playit en segundo plano.
          Start-Process -FilePath "C:\playit.exe" -ArgumentList "" -NoNewWindow -RedirectStandardOutput "$env:TEMP\playit.log" -RedirectStandardError "$env:TEMP\playit_error.log"
          
          echo "Esperando a que playit.gg genere el enlace de reclamación..."
          Start-Sleep -Seconds 20
          
          # Busca el enlace de reclamación en el log.
          $ClaimURL = Get-Content "$env:TEMP\playit.log" | Select-String -Pattern "https://playit.gg/claim/.*" | ForEach-Object { $_.Matches.Value } | Select-Object -Last 1

          if (-not $ClaimURL) {
              Write-Error "Error: No se pudo obtener el enlace de reclamación."
              Write-Host "Revisando logs para depuración:"
              Get-Content "$env:TEMP\playit_error.log"
              Get-Content "$env:TEMP\playit.log"
              exit 1
          }
          
          echo "PLAYIT_CLAIM_URL=$ClaimURL" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Mostrar Instrucciones y Credenciales de Conexión
        run: |
          Write-Host "========================================================================"
          Write-Host "                      ACCIÓN REQUERIDA"
          Write-Host "========================================================================"
          Write-Host ""
          Write-Host "1. Copia la siguiente URL y pégala en tu navegador:"
          Write-Host "   ${{ env.PLAYIT_CLAIM_URL }}"
          Write-Host ""
          Write-Host "2. Inicia sesión en playit.gg para reclamar el agente."
          Write-Host "3. Crea un túnel de tipo TCP para el puerto local 3389."
          Write-Host ""
          Write-Host "========================================================================"
          Write-Host "               CREDENCIALES DE ESCRITORIO REMOTO"
          Write-Host "========================================================================"
          Write-Host ""
          Write-Host "   Usuario:             ${{ env.RDP_USER }}"
          Write-Host "   Contraseña:          ${{ env.RDP_PASSWORD }}"
          Write-Host ""
          Write-Host "========================================================================"
          
      - name: Mantener la Máquina Virtual Activa
        run: Start-Sleep -Seconds 21300
